routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'dashboard','as'=>'dashboard.','name'=>'dashboard'],function(){
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('/tasklist', 'DashboardController@taskList')->name('tasklist');
    Route::get('/manager', 'DashboardController@manager')->name('manager');
    Route::get('/staff', 'DashboardController@staff')->name('staff');
    Route::get('/data/manager', 'DashboardController@datamanagerRefresh');
    Route::get('/data/staff', 'DashboardController@datastaffRefresh');
    Route::get('/payment', 'DashboardController@payment')->name('payment');
});

Route::group(['prefix'=>'role','as'=>'role.','name'=>'role', 'middleware' => 'role:Super Admin'],function(){
    Route::get('/', 'RoleController@index')->name('index');
    Route::post('/', 'RoleController@store')->name('store');
    Route::put('/{id}', 'RoleController@update')->name('update');
    Route::delete('/{id}','RoleController@delete')->name('delete');
});

Route::group(['prefix'=>'user','as'=>'user.','name'=>'user'],function(){
    Route::get('/', 'UserController@index')->name('index')->middleware(['permission:View User']);
    Route::get('/{id}', 'UserController@edit')->name('edit');
    Route::post('/', 'UserController@store')->name('store')->middleware(['role:Super Admin|Manager|Staff']);
    Route::put('/{id}', 'UserController@update')->name('update');
    Route::delete('/{id}','UserController@delete')->name('delete')->middleware(['permission:Manage User']);
});

Route::group(['prefix'=>'department','as'=>'department.','name'=>'department'],function(){
    Route::get('/', 'DepartmentController@index')->name('index');
    Route::get('/{id}', 'DepartmentController@stafflist')->name('stafflist');
    Route::post('/', 'DepartmentController@store')->name('store')->middleware(['permission:Manage Department']);
    Route::put('/{id}', 'DepartmentController@update')->name('update')->middleware(['permission:Manage Department']);
    Route::delete('/{id}','DepartmentController@delete')->name('delete')->middleware(['permission:Manage Department']);
});

Route::group(['prefix'=>'form','as'=>'form.','name'=>'form'],function(){
    Route::get('/', 'FormController@index')->name('index')->middleware(['permission:View Form']);
    Route::get('/create', 'FormController@create')->name('create')->middleware(['permission:Manage Form']);
    Route::get('/{id}', 'FormController@show')->name('show')->middleware(['permission:View Form']);
    Route::get('/{id}/edit', 'FormController@edit')->name('edit')->middleware(['permission:Manage Form']);
    Route::post('/', 'FormController@store')->name('store')->middleware(['permission:Manage Form']);
    Route::put('/{id}', 'FormController@update')->name('update')->middleware(['permission:Manage Form']);
    Route::delete('/{id}','FormController@delete')->name('delete')->middleware(['permission:Manage Form']);

    Route::get('/{id}/sequence', 'FormController@sequence')->name('sequence')->middleware(['permission:View Form']);
    Route::put('/{id}/sequence', 'FormController@storeSequence')->name('storeSequence')->middleware(['permission:Manage Form']);
});

Route::group(['prefix'=>'status','as'=>'status.','name'=>'status'],function(){
    Route::get('/', 'StatusController@index')->name('index')->middleware(['permission:View Status']);
    Route::post('/', 'StatusController@store')->name('store')->middleware(['permission:Manage Status']);
    Route::delete('/{id}','StatusController@delete')->name('delete')->middleware(['permission:Manage Status']);
});

Route::group(['prefix'=>'branch','as'=>'branch.','name'=>'branch'],function(){
    Route::get('/', 'BranchController@index')->name('index')->middleware(['permission:View Branch']);
    Route::post('/', 'BranchController@store')->name('store')->middleware(['permission:Manage Branch']);
    Route::put('/{id}', 'BranchController@update')->name('update')->middleware(['permission:Manage Branch']);
    Route::delete('/{id}','BranchController@delete')->name('delete')->middleware(['permission:Manage Branch']);
});

Route::group(['prefix'=>'order','as'=>'order.','name'=>'order', 'middleware' => 'role:Super Admin|Manager|Staff'],function(){
    Route::get('/', 'OrderController@index')->name('index');
    Route::get('/edit/{id}', 'OrderController@edit')->name('edit');
    Route::get('/refreshList', 'OrderController@refreshList')->name('refreshList');
    Route::get('/detail/{id}', 'OrderController@detail')->name('detail');
    Route::post('/{id}', 'OrderController@store')->name('store');
    Route::delete('/{id}','OrderController@delete')->name('delete');

    Route::get('/form', 'OrderController@selectForm')->name('selectForm');
    Route::get('/form/{id}', 'OrderController@form')->name('form');

    Route::put('/assign', 'OrderController@assignStaff')->name('assignStaff');

    Route::get('/getCustomer/{id}', 'OrderController@getCustomer')->name('getCustomer');
    Route::get('/search', 'OrderController@search')->name('search');

    Route::put('/updateStatus', 'OrderController@updateStatus')->name('updateStatus');
    Route::put('/updateStorage', 'OrderController@updateStorage')->name('updateStorage');
    Route::put('/updatePayment', 'OrderController@updatePayment')->name('updatePayment');
    Route::put('/updateDesign', 'OrderController@updateDesign')->name('updateDesign');
    Route::put('/updateDelivery', 'OrderController@updateDelivery')->name('updateDelivery');
    Route::put('/updateUnpaid', 'OrderController@updateUnpaid')->name('updateUnpaid');

    Route::put('/{id}', 'OrderController@update')->name('update');

});

Route::get('/qr/order/{id}', 'OrderController@qrDetail')->name('qrDetail');
Route::put('/qr/order/{id}', 'OrderController@qrDetailUpdate')->name('qrDetailUpdate');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable implements HasMedia
{
    use Notifiable;
    use HasRoles;
    use SoftDeletes;
    use HasMediaTrait;
    use LogsActivity;

    protected static $logAttributes = ['*'];
    protected static $logOnlyDirty = true;

    protected $guard_name = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'name', 'email', 'password', 'nric', 'contact', 'department_id', 'free_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dates = [
        'free_at',
    ];

    public function department()
    {
        return $this->belongsTo('App\Department');
    }

    public function creators()
    {
        return $this->hasMany('App\Order');
    }

    public function staffs()
    {
        return $this->hasMany('App\Order');
    }

    public function unpaid_approvers()
    {
        return $this->hasMany('App\Order');
    }

    public function customers()
    {
        return $this->hasMany('App\Order');
    }

    public function loggers()
    {
        return $this->hasMany('App\Orderlog');
    }

    public function photo()
    {
        if ($this->getMedia('profilepictures')->last() != null)
        {
            return $this->getMedia('profilepictures')->last()->getUrl();
        }
        else {
            return asset('assets/images/users/no-profile-pic.jpg');
        }
    }

    public function registerMediaCollections()
    {
        $this->addMediaCollection('profilepictures')->singleFile();
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;
use App\Department;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::with('department')->get();
        $permission = Permission::get();
        $role = Role::withCount('users')->get();
        $roleCount = Role::count();
        $department = Department::get();
        return view('user.index', compact('user', 'permission', 'role', 'roleCount', 'department'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request['password'] = bcrypt($request['password']);
        $user = User::create($request->all());
        $user->assignRole($request->role);

        return redirect()->back()->with('message', $user->name.' has been registered.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $role = Role::get();
        $department = Department::get();
        return view('user.edit', compact('user', 'role', 'department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->update($request->all());

        if($request->has('role'))
            $user->syncRoles($request->role);

        if (isset($request['profilepicture']))
            $user->addMediaFromRequest('profilepicture')->toMediaCollection('profilepictures');

        return redirect()->back()->with('message', $user->name.' profile has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('user.index')->with('message', $user->name.' has been deleted.');
    }
}

resources/views/user/edit.blade.php
@extends('layouts.navbar')
@section('breadcrumb', 'User Profile')
@section('content')
<div class="row d-flex no-block justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="d-flex no-block align-items-center col-lg-12 py-3" style="border-bottom: 1px solid #eaeaea;">
                <h4 class="card-title mb-0">USER PROFILE</h4>
            </div>
            <form class="form-horizontal" method="POST" enctype="multipart/form-data" action="{{route('user.update', $user->id)}}">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="card-body">

                    <div class="profile-pic text-center mb-4">
                            <div class="profile-pic mb-3 mt-3">
                                <img src="{!!$user->photo() !!}" width="150" class="rounded-circle" alt="user">
                            </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 text-left control-label col-form-label">Title</label>
                        <div class="col-sm-9">
                            <select class="form-control" name="title">
                                <option {{$user->title == 'Mr.'  ? 'selected' : ''}}>Mr.</option>
                                <option {{$user->title == 'Mrs.'  ? 'selected' : ''}}>Mrs.</option>
                                <option {{$user->title == 'Miss'  ? 'selected' : ''}}>Miss</option>
                                <option {{$user->title == 'Sir'  ? 'selected' : ''}}>Sir</option>
                                <option {{$user->title == 'Madam'  ? 'selected' : ''}}>Madam</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="fname" class="col-sm-3 text-left control-label col-form-label">Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" value="{{$user->name}}" name="name" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 text-left control-label col-form-label">IC Number</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" value="{{$user->nric}}" name="nric" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 text-left control-label col-form-label">Mobile No</label>
                        <div class="col-sm-9">
                            <input type="text" pattern="[0-9]+" class="form-control" value="{{$user->contact}}" name="contact" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 text-left control-label col-form-label">Email</label>
                        <div class="col-sm-9">
                            <input type="email" class="form-control" value="{{$user->email}}" name="email" required>
                        </div>
                    </div>
                    <div class="form-group row">
                            <label class="col-sm-3 text-left control-label col-form-label">Department</label>
                            <div class="col-sm-9">
                            @role('Super Admin')
                                <select class="form-control" name="department_id">
                                    <option value="">Unassigned</option>
                                    @foreach($department as $d)
                                    <option value="{{$d->id}}" {{$user->department_id == $d->id  ? 'selected' : ''}}>{{$d->name}}</option>
                                    @endforeach
                                </select>
                            @else
                            <label class="text-left control-label col-form-label">{{$user->department['name']}}</label>
                            @endrole
                            </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 text-left control-label col-form-label">Role</label>
                        <div class="col-sm-9">
                            @role('Super Admin')
                            <select class="form-control" name="role">
                                @foreach($role as $r)
                                <option {{$user->getRoleNames()->first() == $r->name  ? 'selected' : ''}}>{{$r->name}}</option>
                                @endforeach
                            </select>
                            @else
                            <label class="text-left control-label col-form-label">{{$user->getRoleNames()->first()}}</label>
                            @endrole
                        </div>
                    </div>
                    <div class="form-group row">
                            <label class="col-sm-3 text-left control-label col-form-label">Profile Picture</label>
                            <div class="input-group mb-3 col-sm-9">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Upload</span>
                                </div>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" name="profilepicture" onchange="ValidateSize(this)">
                                    <label id="img" class="custom-file-label">Choose file</label>
                                </div>
                            </div>
                    </div>
                </div>
                <hr class="mb-0">
                <div class="card-body">
                    <div class="row ml-2">
                        <div class="form-group mb-0 text-left">
                            <button type="submit" class="btn btn-info waves-effect waves-light">Save</button>
                        </div>
                    </form>
                        <form action="{{route('user.delete', $user->id)}}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger waves-effect waves-light ml-2">Delete</button>
                        </form>
                    </div>
                </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection

@section('script')
<script>
    function ValidateSize(file) {
        var FileSize = file.files[0].size / 1024 / 1024; // in MB
        if (FileSize > 1) {
            swal("Warning", "File size exceeds 1 MB!", "warning");
            $(file).val(''); //for clearing with Jquery
            $('#img').html('Choose file');
        }
        else{
            $('#img').html(file.files[0].name);
        }
    }
</script>
<!--Custom JavaScript -->
<script src="{{ asset('assets/libs/sweetalert2/dist/sweetalert2.all.min.js') }}"></script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.navbar')
@section('breadcrumb', 'User List')
@section('content')
<div class="col-sm-12">
    <div class="card">
        <div class="d-flex no-block align-items-center col-lg-12 py-3" style="border-bottom: 1px solid #eaeaea;">
            <h4 class="card-title mb-0 ml-4">USER LIST</h4>
            <div class="ml-auto mr-4">
                @can('Manage User')
                <div class="btn-group">
                    <button class="btn btn-info btn-rounded" data-toggle="modal" data-target="#createuser">
                        <i class="mdi mdi-account-plus mr-2"></i>Add User
                    </button>
                </div>
                @endcan
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive col-lg-12">
                <table id="userTable" class="table no-wrap user-table mb-3">
                    <thead>
                        <tr>
                            <th>NAME</th>
                            <th>IC NUMBER</th>
                            <th>EMAIL</th>
                            <th>MOBILE NO</th>
                            <th>DEPARTMENT</th>
                            <th>ROLE</th>
                            <th>JOINING DATE</th>
                            <th>ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($user as $u)
                        <tr>
                            <td><img src="{!! $u->photo() !!}" alt="user" class="rounded-circle" width="30" /> {{$u->name}}
                            </td>
                            <td>{{$u->nric}}</td>
                            <td>{{$u->email}}</td>
                            <td>{{$u->contact}}</td>
                            <td>{{$u->department['name']}}</td>
                            <td><span class="label label-danger">{{$u->getRoleNames()->first()}}</span></td>
                            <td>{{date('d-m-Y', strtotime($u->created_at))}}</td>
                            <td>
                                @can('Manage User')<a href="{{route('user.edit', $u->id)}}" class="btn btn-outline-info btn-circle btn-sm btn-circle ml-2"><i class="ti-pencil-alt"></i> </a>@endcan

                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Create UserModal -->
<div class="modal fade" id="createuser" tabindex="-1" role="dialog" aria-labelledby="createModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" action="{{ route('user.store') }}">
                @csrf
                <div class="modal-header">
                    <h4 class="modal-title" id="createModalLabel"><i class="ti-user ml-2 mr-2"></i> Add New
                        User</h4>
                    <button class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="input-group mb-3">
                        <select class="form-control" name="title" required>
                            <option value="" disabled selected>Select Title</option>
                            <option>Mr</option>
                            <option>Mrs</option>
                            <option>Miss</option>
                            <option>Sir</option>
                            <option>Madam</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Enter Name Here" name="name" required>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Enter IC Number Here" name="nric" required>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" pattern="[0-9]+" placeholder="Enter mobile number here (Number only)" name="contact"
                            required>
                    </div>
                    <div class="input-group mb-3">
                        <input type="Email" class="form-control" placeholder="Enter Email Here" name="email" required>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Enter Password Here" name="password"
                            required>
                    </div>
                    <div class="input-group mb-3">
                        <select class="form-control" name="role" required>
                            <option value="" disabled selected>Select Role</option>
                            @foreach($role as $r)
                            <option>{{$r->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <select class="form-control" name="department_id">
                            <option value="">Select Department</option>
                            @foreach($department as $d)
                            <option value="{{$d->id}}">{{$d->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success"><i class="ti-save mr-2"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function () {
        $('#userTable').DataTable();
    });
</script>
@endsection