routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'dashboard','as'=>'dashboard.','name'=>'dashboard'],function(){
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('/tasklist', 'DashboardController@taskList')->name('tasklist');
    Route::get('/manager', 'DashboardController@manager')->name('manager');
    Route::get('/staff', 'DashboardController@staff')->name('staff');
    Route::get('/data/manager', 'DashboardController@datamanagerRefresh');
    Route::get('/data/staff', 'DashboardController@datastaffRefresh');
    Route::get('/payment', 'DashboardController@payment')->name('payment');
});

Route::group(['prefix'=>'role','as'=>'role.','name'=>'role', 'middleware' => 'role:Super Admin'],function(){
    Route::get('/', 'RoleController@index')->name('index');
    Route::post('/', 'RoleController@store')->name('store');
    Route::put('/{id}', 'RoleController@update')->name('update');
    Route::delete('/{id}','RoleController@delete')->name('delete');
});

Route::group(['prefix'=>'user','as'=>'user.','name'=>'user'],function(){
    Route::get('/', 'UserController@index')->name('index')->middleware(['permission:View User']);
    Route::get('/{id}', 'UserController@edit')->name('edit');
    Route::post('/', 'UserController@store')->name('store')->middleware(['role:Super Admin|Manager|Staff']);
    Route::put('/{id}', 'UserController@update')->name('update');
    Route::delete('/{id}','UserController@delete')->name('delete')->middleware(['permission:Manage User']);
});

Route::group(['prefix'=>'department','as'=>'department.','name'=>'department'],function(){
    Route::get('/', 'DepartmentController@index')->name('index');
    Route::get('/{id}', 'DepartmentController@stafflist')->name('stafflist');
    Route::post('/', 'DepartmentController@store')->name('store')->middleware(['permission:Manage Department']);
    Route::put('/{id}', 'DepartmentController@update')->name('update')->middleware(['permission:Manage Department']);
    Route::delete('/{id}','DepartmentController@delete')->name('delete')->middleware(['permission:Manage Department']);
});

Route::group(['prefix'=>'form','as'=>'form.','name'=>'form'],function(){
    Route::get('/', 'FormController@index')->name('index')->middleware(['permission:View Form']);
    Route::get('/create', 'FormController@create')->name('create')->middleware(['permission:Manage Form']);
    Route::get('/{id}', 'FormController@show')->name('show')->middleware(['permission:View Form']);
    Route::get('/{id}/edit', 'FormController@edit')->name('edit')->middleware(['permission:Manage Form']);
    Route::post('/', 'FormController@store')->name('store')->middleware(['permission:Manage Form']);
    Route::put('/{id}', 'FormController@update')->name('update')->middleware(['permission:Manage Form']);
    Route::delete('/{id}','FormController@delete')->name('delete')->middleware(['permission:Manage Form']);

    Route::get('/{id}/sequence', 'FormController@sequence')->name('sequence')->middleware(['permission:View Form']);
    Route::put('/{id}/sequence', 'FormController@storeSequence')->name('storeSequence')->middleware(['permission:Manage Form']);
});

Route::group(['prefix'=>'status','as'=>'status.','name'=>'status'],function(){
    Route::get('/', 'StatusController@index')->name('index')->middleware(['permission:View Status']);
    Route::post('/', 'StatusController@store')->name('store')->middleware(['permission:Manage Status']);
    Route::delete('/{id}','StatusController@delete')->name('delete')->middleware(['permission:Manage Status']);
});

Route::group(['prefix'=>'branch','as'=>'branch.','name'=>'branch'],function(){
    Route::get('/', 'BranchController@index')->name('index')->middleware(['permission:View Branch']);
    Route::post('/', 'BranchController@store')->name('store')->middleware(['permission:Manage Branch']);
    Route::put('/{id}', 'BranchController@update')->name('update')->middleware(['permission:Manage Branch']);
    Route::delete('/{id}','BranchController@delete')->name('delete')->middleware(['permission:Manage Branch']);
});

Route::group(['prefix'=>'order','as'=>'order.','name'=>'order', 'middleware' => 'role:Super Admin|Manager|Staff'],function(){
    Route::get('/', 'OrderController@index')->name('index');
    Route::get('/edit/{id}', 'OrderController@edit')->name('edit');
    Route::get('/refreshList', 'OrderController@refreshList')->name('refreshList');
    Route::get('/detail/{id}', 'OrderController@detail')->name('detail');
    Route::post('/{id}', 'OrderController@store')->name('store');
    Route::delete('/{id}','OrderController@delete')->name('delete');

    Route::get('/form', 'OrderController@selectForm')->name('selectForm');
    Route::get('/form/{id}', 'OrderController@form')->name('form');

    Route::put('/assign', 'OrderController@assignStaff')->name('assignStaff');

    Route::get('/getCustomer/{id}', 'OrderController@getCustomer')->name('getCustomer');
    Route::get('/search', 'OrderController@search')->name('search');

    Route::put('/updateStatus', 'OrderController@updateStatus')->name('updateStatus');
    Route::put('/updateStorage', 'OrderController@updateStorage')->name('updateStorage');
    Route::put('/updatePayment', 'OrderController@updatePayment')->name('updatePayment');
    Route::put('/updateDesign', 'OrderController@updateDesign')->name('updateDesign');
    Route::put('/updateDelivery', 'OrderController@updateDelivery')->name('updateDelivery');
    Route::put('/updateUnpaid', 'OrderController@updateUnpaid')->name('updateUnpaid');

    Route::put('/{id}', 'OrderController@update')->name('update');

});

Route::get('/qr/order/{id}', 'OrderController@qrDetail')->name('qrDetail');
Route::put('/qr/order/{id}', 'OrderController@qrDetailUpdate')->name('qrDetailUpdate');

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;

class Department extends Model
{
    use SoftDeletes;
    use LogsActivity;

    protected static $logAttributes = ['*'];
    protected static $logOnlyDirty = true;

    protected $fillable = [
        'name',
    ];

    public function users()
    {
        return $this->hasMany('App\User');
    }

    public function orders()
    {
        return $this->hasMany('App\Order');
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Department;
use App\User;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $department = Department::withCount('users')->get();
        return view('department.index', compact('department'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $department = Department::create($request->all());

        return redirect()->back()->with('message', $department->name.' department has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function stafflist($id)
    {
        $staff = User::where('department_id', $id)->get();
        $department = Department::where('id', $id)->value('name');

        return view('department.staff', compact('staff', 'department'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $department = Department::find($id);
        $department->update($request->all());

        return redirect()->back()->with('message', $department->name.' department has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $department = Department::find($id);
        $department->delete();

        return redirect()->back()->with('message', $department->name.'  department has been deleted.');
    }
}

resources/views/department/index.blade.php
@extends('layouts.navbar')
@section('breadcrumb', 'Department List')
@section('content')
<div class="col-sm-12">
    <div class="card">
            <div class="d-flex no-block align-items-center col-lg-12 py-3" style="border-bottom: 1px solid #eaeaea;">
                    <h4 class="card-title mb-0 ml-4">DEPARTMENT LIST</h4>
                    <div class="ml-auto mr-4">
                        @can('Manage Department')
                        <div class="btn-group">
                            <button class="btn btn-info btn-rounded" data-toggle="modal" data-target="#createdepartment">
                                <i class="mdi mdi-briefcase mr-2"></i>Add New Department
                            </button>
                        </div>
                        @endcan
                    </div>
                </div>
        <div class="card-body">
            <div class="table-responsive col-lg-12">
                <table id="departmentTable" class="table no-wrap user-table mb-3">
                    <thead>
                        <tr>
                            <th>DEPARTMENT NAME</th>
                            <th>TOTAL STAFF</th>
                            <th>ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($department as $d)
                        <tr>
                            <td>{{$d->name}}</td>
                            <td>{{$d->users_count}}</td>
                            <td>
                                <a href="{{route('department.stafflist', $d->id)}}" class="btn btn-outline-info btn-circle btn-sm btn-circle ml-2"><i class="ti-eye"></i></a>
                                @can('Manage Department')
                                <button class="btn btn-outline-info btn-circle btn-sm btn-circle ml-2" data-toggle="modal" data-target="#managedepartment{{$d->id}}"><i class="ti-pencil-alt"></i></button>
                                @endcan
                            </td>
                        </tr>

                        <!-- Manage Department Modal -->
                        <div class="modal fade" id="managedepartment{{$d->id}}" tabindex="-1" role="dialog"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <form class="form-horizontal" method="POST"
                                        action="{{ route('department.update', $d->id) }}">
                                        {{ csrf_field() }}
                                        {{ method_field('PUT') }}
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="myModalLabel">Manage Department</h4>
                                            <button type="button" class="close" data-dismiss="modal"
                                                aria-hidden="true">×</button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label class="col-md-12">Name of Department</label>
                                                <div class="col-md-12">
                                                    <input type="text" class="form-control" value="{{$d->name}}"
                                                        name="name" required />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-dismiss="modal">Cancel</button>
                                            <button type="submit" class="btn btn-success"><i class="ti-save mr-2"></i>
                                                Save</button>
                                    </form>
                                    <form action="{{ route('department.delete', $d->id ) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="btn btn-danger"><i class="ti-trash mr-2"></i>
                                            Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Create Department Modal -->
<div class="modal fade" id="createdepartment" tabindex="-1" role="dialog" aria-labelledby="createModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" action="{{ route('department.store') }}">
                @csrf
                <div class="modal-header">
                    <h4 class="modal-title" id="createModalLabel"><i class="mdi mdi-briefcase mr-2"></i> Add New
                        Department</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Enter Department Name Here" name="name"
                            required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success"><i class="ti-save mr-2"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function () {
        $('#departmentTable').DataTable();
    });
</script>
@endsection

resources/views/department/staff.blade.php
@extends('layouts.navbar')
@section('breadcrumb', 'Department / '.$department)
@section('content')
<div class="col-sm-12">
    <div class="card">
        <div class="card-body">
            <div class="d-flex no-block align-items-center mb-4">
                <h4 class="card-title">{{$department}} Department Staff</h4>
            </div>
            <div class="table-responsive col-lg-12">
                <table id="userTable" class="table no-wrap user-table mb-3">
                    <thead>
                        <tr>
                            <th>NAME</th>
                            <th>IC NUMBER</th>
                            <th>EMAIL</th>
                            <th>MOBILE NO</th>
                            <th>JOINING DATE</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($staff as $s)
                        <tr>
                            <td>{{$s->name}}</td>
                            <td>{{$s->nric}}</td>
                            <td>{{$s->email}}</td>
                            <td>{{$s->contact}}</td>
                            <td>{{date('d-m-Y', strtotime($s->created_at))}}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection